# Model Training Testing and Evaluation 
This notebook contains the code relating to training models and evaluating them

In [4]:
import pandas as pd 
import numpy as np

In [14]:
df = pd.read_csv('merged.csv').set_index('tconst')
df.dropna(inplace=True) 
df

,averageRating,numVotes,isAdult,startYear,runtimeMinutes,actor_nm0555550,actor_nm0245596,actor_nm0068501,actor_nm0001825,actor_nm0138287,...,writers_nm0244101,writers_nm0905942,writers_nm0630331,writers_nm0963380,writers_nm0307222,writers_nm4952714,writers_nm0777463,writers_nm1558799,writers_nm9946617,writers_non_100_category
tconst,,,,,,,,,,,,,,,,,,,,,
tt0926063,5.8,11626,0,2008.0,87.0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
tt0110116,7.4,24628,0,1994.0,121.0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
tt0083655,6.0,1898,0,1982.0,102.0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
tt0405866,6.6,2744,0,2004.0,111.0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
tt5537140,5.6,4526,0,2016.0,132.0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
tt0120118,6.3,3441,0,1996.0,93.0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
tt0116531,5.5,13343,0,1996.0,86.0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
tt0026138,7.8,47291,0,1935.0,75.0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
tt0214841,7.4,2265,0,1980.0,159.0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
tt0279781,5.4,15590,0,2002.0,93.0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [15]:
from sklearn.model_selection import train_test_split

x_train, x_test = train_test_split(df, test_size=0.25, shuffle=True)  

y_train = list(x_train['averageRating'])
y_test = list(x_test['averageRating'])

x_train.drop(columns=['averageRating','numVotes'], inplace=True) 
x_test.drop(columns=['averageRating','numVotes'], inplace=True)

/Users/ryankennedy/opt/anaconda3/lib/python3.7/site-packages/pandas/core/frame.py:4102: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  errors=errors,

In [22]:
from sklearn.metrics import mean_squared_error 
from sklearn.metrics import r2_score 

def eval_preds(preds, actual):
    mse = mean_squared_error(actual, preds) 
    r2 = r2_score(actual, preds)
    
    print(f"MSE: {mse} R2: {r2}")

In [23]:
from sklearn.linear_model import LinearRegression

clf = LinearRegression().fit(x_train, y_train)

In [25]:
preds = clf.predict(x_test)

for idx in range(10):
    print(f"Actual {y_test[idx]} - Pred: {preds[idx]}")

Actual 7.4 - Pred: 5.8687578515119725
Actual 4.9 - Pred: 6.0377905680377815
Actual 6.0 - Pred: 6.110990825247693
Actual 7.2 - Pred: 6.6107305818910795
Actual 8.2 - Pred: 7.710545545024182
Actual 5.3 - Pred: 6.613311974625464
Actual 6.3 - Pred: 6.094557577522789
Actual 6.0 - Pred: 6.325500876591967
Actual 6.3 - Pred: 6.641142092975347
Actual 7.9 - Pred: 6.317110760113884